version: "3"
services:
    gpsd:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 2947:2947
        restart: always
        entrypoint:
        - /usr/bin/bash
        - -c
        - /init