version: "3"
services:
    gpsd:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 2947:2947
        restart: always
        entrypoint:
        - /bin/bash
        - -c
        - /init
        volumes:
            - ./vol/docker-gpsd/var/lib/ntp/:/var/lib/ntp/