version: "3"

volumes:
  gpsdntpd:

services:
  gpsd:
    container_name: gpsdntpd
    hostname: gpsdntpd
    tty: true
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2947:2947/tcp"
      - "123:123/udp"
    restart: always
    environment:
      - GPS_DEVICE=${GPS_DEVICE}
      - TZ=${TZ}
    entrypoint:
    - /bin/bash
    - -c
    - /init
    volumes:
      - ./vol/docker-gpsd-ntpd/var/lib/ntp:/var/lib/ntp
    tmpfs:
      - /var/log:size=32M